source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SocialQ_Example', :exclusive => true do
  pod 'SocialQ', :path => '../'
end

target 'SocialQ_Tests', :exclusive => true do
  pod 'SocialQ', :path => '../'

  
end
